/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.creek;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    final Library classUnderTest = new Library();
    assertThat(classUnderTest.someLibraryMethod(), is(true));
  }
}
